# Generated by Django 4.1.1 on 2023-02-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cateory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=128, null=True)),
                ('imageScreensaver', models.ImageField(default='static/img/quizs_img/imageScreensavers/47899679c157cb3b7fb73e2134086efb.jpg', null=True, upload_to='static/img/quizs_img/imageScreensavers')),
                ('category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizs.cateory')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=64)),
                ('image', models.ImageField(null=True, upload_to='static/img/quizs_img/questions_img')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128, null=True)),
                ('correct', models.BooleanField()),
                ('question_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.questions')),
            ],
        ),
    ]
